// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: blockchain_network.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBlockchainNetwork = `-- name: CreateBlockchainNetwork :one
INSERT INTO blockchain_networks (
    code,
    name,
    chain_id,
    explorer,
    description,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, code, name, chain_id, explorer, description, is_active, created_at, updated_at
`

type CreateBlockchainNetworkParams struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	ChainID     int32          `json:"chain_id"`
	Explorer    string         `json:"explorer"`
	Description sql.NullString `json:"description"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateBlockchainNetwork(ctx context.Context, arg CreateBlockchainNetworkParams) (BlockchainNetwork, error) {
	row := q.db.QueryRowContext(ctx, createBlockchainNetwork,
		arg.Code,
		arg.Name,
		arg.ChainID,
		arg.Explorer,
		arg.Description,
		arg.IsActive,
	)
	var i BlockchainNetwork
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ChainID,
		&i.Explorer,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateBlockchainNetwork = `-- name: DeactivateBlockchainNetwork :exec
UPDATE blockchain_networks
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateBlockchainNetwork(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateBlockchainNetwork, id)
	return err
}

const getBlockchainNetwork = `-- name: GetBlockchainNetwork :one
SELECT id, code, name, chain_id, explorer, description, is_active, created_at, updated_at FROM blockchain_networks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBlockchainNetwork(ctx context.Context, id uuid.UUID) (BlockchainNetwork, error) {
	row := q.db.QueryRowContext(ctx, getBlockchainNetwork, id)
	var i BlockchainNetwork
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ChainID,
		&i.Explorer,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlockchainNetworkByCode = `-- name: GetBlockchainNetworkByCode :one
SELECT id, code, name, chain_id, explorer, description, is_active, created_at, updated_at FROM blockchain_networks
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetBlockchainNetworkByCode(ctx context.Context, code string) (BlockchainNetwork, error) {
	row := q.db.QueryRowContext(ctx, getBlockchainNetworkByCode, code)
	var i BlockchainNetwork
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ChainID,
		&i.Explorer,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBlockchainNetworks = `-- name: ListActiveBlockchainNetworks :many
SELECT id, code, name, chain_id, explorer, description, is_active, created_at, updated_at FROM blockchain_networks
WHERE is_active = true
ORDER BY name ASC
`

func (q *Queries) ListActiveBlockchainNetworks(ctx context.Context) ([]BlockchainNetwork, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBlockchainNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlockchainNetwork{}
	for rows.Next() {
		var i BlockchainNetwork
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ChainID,
			&i.Explorer,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBlockchainNetworks = `-- name: ListAllBlockchainNetworks :many
SELECT id, code, name, chain_id, explorer, description, is_active, created_at, updated_at FROM blockchain_networks
ORDER BY name ASC
`

func (q *Queries) ListAllBlockchainNetworks(ctx context.Context) ([]BlockchainNetwork, error) {
	rows, err := q.db.QueryContext(ctx, listAllBlockchainNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlockchainNetwork{}
	for rows.Next() {
		var i BlockchainNetwork
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ChainID,
			&i.Explorer,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlockchainNetwork = `-- name: UpdateBlockchainNetwork :one
UPDATE blockchain_networks
SET name = $2, chain_id = $3, explorer = $4, description = $5, is_active = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, code, name, chain_id, explorer, description, is_active, created_at, updated_at
`

type UpdateBlockchainNetworkParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	ChainID     int32          `json:"chain_id"`
	Explorer    string         `json:"explorer"`
	Description sql.NullString `json:"description"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateBlockchainNetwork(ctx context.Context, arg UpdateBlockchainNetworkParams) (BlockchainNetwork, error) {
	row := q.db.QueryRowContext(ctx, updateBlockchainNetwork,
		arg.ID,
		arg.Name,
		arg.ChainID,
		arg.Explorer,
		arg.Description,
		arg.IsActive,
	)
	var i BlockchainNetwork
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ChainID,
		&i.Explorer,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
