// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deposit_request.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelDepositRequest = `-- name: CancelDepositRequest :one
UPDATE deposit_requests
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
RETURNING id, customer_id, wallet_id, assigned_address, network, token, expected_amount, received_amount, status, transaction_id, expires_at, completed_at, created_at, updated_at
`

func (q *Queries) CancelDepositRequest(ctx context.Context, id uuid.UUID) (DepositRequest, error) {
	row := q.db.QueryRowContext(ctx, cancelDepositRequest, id)
	var i DepositRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.WalletID,
		&i.AssignedAddress,
		&i.Network,
		&i.Token,
		&i.ExpectedAmount,
		&i.ReceivedAmount,
		&i.Status,
		&i.TransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDepositRequest = `-- name: CreateDepositRequest :one
INSERT INTO deposit_requests (
  customer_id,
  wallet_id,
  assigned_address,
  network,
  token,
  expected_amount,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, customer_id, wallet_id, assigned_address, network, token, expected_amount, received_amount, status, transaction_id, expires_at, completed_at, created_at, updated_at
`

type CreateDepositRequestParams struct {
	CustomerID      string         `json:"customer_id"`
	WalletID        uuid.UUID      `json:"wallet_id"`
	AssignedAddress string         `json:"assigned_address"`
	Network         string         `json:"network"`
	Token           string         `json:"token"`
	ExpectedAmount  sql.NullString `json:"expected_amount"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateDepositRequest(ctx context.Context, arg CreateDepositRequestParams) (DepositRequest, error) {
	row := q.db.QueryRowContext(ctx, createDepositRequest,
		arg.CustomerID,
		arg.WalletID,
		arg.AssignedAddress,
		arg.Network,
		arg.Token,
		arg.ExpectedAmount,
		arg.ExpiresAt,
	)
	var i DepositRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.WalletID,
		&i.AssignedAddress,
		&i.Network,
		&i.Token,
		&i.ExpectedAmount,
		&i.ReceivedAmount,
		&i.Status,
		&i.TransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireDepositRequests = `-- name: ExpireDepositRequests :many
UPDATE deposit_requests
SET status = 'expired', updated_at = NOW()
WHERE status IN ('pending', 'partial')
  AND expires_at IS NOT NULL
  AND expires_at < NOW()
RETURNING id, customer_id, wallet_id, assigned_address, network, token, expected_amount, received_amount, status, transaction_id, expires_at, completed_at, created_at, updated_at
`

func (q *Queries) ExpireDepositRequests(ctx context.Context) ([]DepositRequest, error) {
	rows, err := q.db.QueryContext(ctx, expireDepositRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DepositRequest{}
	for rows.Next() {
		var i DepositRequest
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.WalletID,
			&i.AssignedAddress,
			&i.Network,
			&i.Token,
			&i.ExpectedAmount,
			&i.ReceivedAmount,
			&i.Status,
			&i.TransactionID,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepositRequest = `-- name: GetDepositRequest :one
SELECT id, customer_id, wallet_id, assigned_address, network, token, expected_amount, received_amount, status, transaction_id, expires_at, completed_at, created_at, updated_at FROM deposit_requests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDepositRequest(ctx context.Context, id uuid.UUID) (DepositRequest, error) {
	row := q.db.QueryRowContext(ctx, getDepositRequest, id)
	var i DepositRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.WalletID,
		&i.AssignedAddress,
		&i.Network,
		&i.Token,
		&i.ExpectedAmount,
		&i.ReceivedAmount,
		&i.Status,
		&i.TransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositRequestByCustomer = `-- name: GetDepositRequestByCustomer :many
SELECT id, customer_id, wallet_id, assigned_address, network, token, expected_amount, received_amount, status, transaction_id, expires_at, completed_at, created_at, updated_at FROM deposit_requests
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetDepositRequestByCustomerParams struct {
	CustomerID string `json:"customer_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetDepositRequestByCustomer(ctx context.Context, arg GetDepositRequestByCustomerParams) ([]DepositRequest, error) {
	rows, err := q.db.QueryContext(ctx, getDepositRequestByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DepositRequest{}
	for rows.Next() {
		var i DepositRequest
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.WalletID,
			&i.AssignedAddress,
			&i.Network,
			&i.Token,
			&i.ExpectedAmount,
			&i.ReceivedAmount,
			&i.Status,
			&i.TransactionID,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingDepositByAddress = `-- name: GetPendingDepositByAddress :one
SELECT id, customer_id, wallet_id, assigned_address, network, token, expected_amount, received_amount, status, transaction_id, expires_at, completed_at, created_at, updated_at FROM deposit_requests
WHERE assigned_address = $1 
  AND status IN ('pending', 'partial')
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingDepositByAddress(ctx context.Context, assignedAddress string) (DepositRequest, error) {
	row := q.db.QueryRowContext(ctx, getPendingDepositByAddress, assignedAddress)
	var i DepositRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.WalletID,
		&i.AssignedAddress,
		&i.Network,
		&i.Token,
		&i.ExpectedAmount,
		&i.ReceivedAmount,
		&i.Status,
		&i.TransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingDeposits = `-- name: ListPendingDeposits :many
SELECT id, customer_id, wallet_id, assigned_address, network, token, expected_amount, received_amount, status, transaction_id, expires_at, completed_at, created_at, updated_at FROM deposit_requests
WHERE status IN ('pending', 'partial')
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListPendingDeposits(ctx context.Context) ([]DepositRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DepositRequest{}
	for rows.Next() {
		var i DepositRequest
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.WalletID,
			&i.AssignedAddress,
			&i.Network,
			&i.Token,
			&i.ExpectedAmount,
			&i.ReceivedAmount,
			&i.Status,
			&i.TransactionID,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepositRequestStatus = `-- name: UpdateDepositRequestStatus :one
UPDATE deposit_requests
SET 
  status = $2,
  received_amount = $3,
  transaction_id = $4,
  completed_at = CASE WHEN $2 = 'completed' THEN NOW() ELSE completed_at END,
  updated_at = NOW()
WHERE id = $1
RETURNING id, customer_id, wallet_id, assigned_address, network, token, expected_amount, received_amount, status, transaction_id, expires_at, completed_at, created_at, updated_at
`

type UpdateDepositRequestStatusParams struct {
	ID             uuid.UUID      `json:"id"`
	Status         string         `json:"status"`
	ReceivedAmount sql.NullString `json:"received_amount"`
	TransactionID  uuid.NullUUID  `json:"transaction_id"`
}

func (q *Queries) UpdateDepositRequestStatus(ctx context.Context, arg UpdateDepositRequestStatusParams) (DepositRequest, error) {
	row := q.db.QueryRowContext(ctx, updateDepositRequestStatus,
		arg.ID,
		arg.Status,
		arg.ReceivedAmount,
		arg.TransactionID,
	)
	var i DepositRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.WalletID,
		&i.AssignedAddress,
		&i.Network,
		&i.Token,
		&i.ExpectedAmount,
		&i.ReceivedAmount,
		&i.Status,
		&i.TransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
