// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: failed_api_request.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createFailedAPIRequest = `-- name: CreateFailedAPIRequest :one
insert into failed_api_requests (
    deposit_request_id,
    withdrawal_request_id,
    body,
    error) values ($1,$2,$3,$4) 
    returning id, deposit_request_id, withdrawal_request_id, body, error, last_attempt, created_at
`

type CreateFailedAPIRequestParams struct {
	DepositRequestID    uuid.NullUUID   `json:"deposit_request_id"`
	WithdrawalRequestID uuid.NullUUID   `json:"withdrawal_request_id"`
	Body                json.RawMessage `json:"body"`
	Error               string          `json:"error"`
}

func (q *Queries) CreateFailedAPIRequest(ctx context.Context, arg CreateFailedAPIRequestParams) (FailedApiRequest, error) {
	row := q.db.QueryRowContext(ctx, createFailedAPIRequest,
		arg.DepositRequestID,
		arg.WithdrawalRequestID,
		arg.Body,
		arg.Error,
	)
	var i FailedApiRequest
	err := row.Scan(
		&i.ID,
		&i.DepositRequestID,
		&i.WithdrawalRequestID,
		&i.Body,
		&i.Error,
		&i.LastAttempt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFailedAPIRequest = `-- name: DeleteFailedAPIRequest :exec
DELETE FROM failed_api_requests
WHERE id = $1
`

func (q *Queries) DeleteFailedAPIRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFailedAPIRequest, id)
	return err
}

const getPendingFailedAPIRequests = `-- name: GetPendingFailedAPIRequests :many
SELECT id, deposit_request_id, withdrawal_request_id, body, error, last_attempt, created_at FROM failed_api_requests
`

func (q *Queries) GetPendingFailedAPIRequests(ctx context.Context) ([]FailedApiRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFailedAPIRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailedApiRequest{}
	for rows.Next() {
		var i FailedApiRequest
		if err := rows.Scan(
			&i.ID,
			&i.DepositRequestID,
			&i.WithdrawalRequestID,
			&i.Body,
			&i.Error,
			&i.LastAttempt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFailedAPIRequestAttempt = `-- name: UpdateFailedAPIRequestAttempt :one
UPDATE failed_api_requests
SET last_attempt = NOW()
WHERE id = $1
RETURNING id, deposit_request_id, withdrawal_request_id, body, error, last_attempt, created_at
`

func (q *Queries) UpdateFailedAPIRequestAttempt(ctx context.Context, id uuid.UUID) (FailedApiRequest, error) {
	row := q.db.QueryRowContext(ctx, updateFailedAPIRequestAttempt, id)
	var i FailedApiRequest
	err := row.Scan(
		&i.ID,
		&i.DepositRequestID,
		&i.WithdrawalRequestID,
		&i.Body,
		&i.Error,
		&i.LastAttempt,
		&i.CreatedAt,
	)
	return i, err
}
