// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BlockchainNetwork struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	ChainID     int32          `json:"chain_id"`
	Explorer    string         `json:"explorer"`
	Description sql.NullString `json:"description"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type DepositRequest struct {
	ID              uuid.UUID      `json:"id"`
	CustomerID      string         `json:"customer_id"`
	WalletID        uuid.UUID      `json:"wallet_id"`
	AssignedAddress string         `json:"assigned_address"`
	Network         string         `json:"network"`
	Token           string         `json:"token"`
	ExpectedAmount  sql.NullString `json:"expected_amount"`
	ReceivedAmount  sql.NullString `json:"received_amount"`
	Status          string         `json:"status"`
	TransactionID   uuid.NullUUID  `json:"transaction_id"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Token struct {
	ID              uuid.UUID      `json:"id"`
	Code            string         `json:"code"`
	Name            string         `json:"name"`
	Symbol          string         `json:"symbol"`
	Decimals        int32          `json:"decimals"`
	ContractAddress sql.NullString `json:"contract_address"`
	NetworkCode     string         `json:"network_code"`
	TokenType       string         `json:"token_type"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Transaction struct {
	ID              uuid.UUID      `json:"id"`
	WalletID        uuid.NullUUID  `json:"wallet_id"`
	WebhookID       string         `json:"webhook_id"`
	EventID         string         `json:"event_id"`
	Network         string         `json:"network"`
	TransactionHash string         `json:"transaction_hash"`
	BlockNumber     string         `json:"block_number"`
	FromAddress     string         `json:"from_address"`
	ToAddress       string         `json:"to_address"`
	Value           string         `json:"value"`
	Asset           string         `json:"asset"`
	Category        string         `json:"category"`
	TransactionType sql.NullString `json:"transaction_type"`
	Status          sql.NullString `json:"status"`
	IsMatched       sql.NullBool   `json:"is_matched"`
	GasFee          sql.NullString `json:"gas_fee"`
	Confirmations   sql.NullInt32  `json:"confirmations"`
	ContractAddress sql.NullString `json:"contract_address"`
	Decimals        sql.NullInt32  `json:"decimals"`
	RawValue        sql.NullString `json:"raw_value"`
	BlockTimestamp  string         `json:"block_timestamp"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Wallet struct {
	ID         uuid.UUID      `json:"id"`
	WalletType string         `json:"wallet_type"`
	Blockchain string         `json:"blockchain"`
	Token      string         `json:"token"`
	Address    string         `json:"address"`
	PublicKey  string         `json:"public_key"`
	PrivateKey string         `json:"private_key"`
	Balance    sql.NullString `json:"balance"`
	IsActive   sql.NullBool   `json:"is_active"`
	LastSyncAt sql.NullTime   `json:"last_sync_at"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type WebhookRegistration struct {
	ID               uuid.UUID `json:"id"`
	WalletID         uuid.UUID `json:"wallet_id"`
	AlchemyWebhookID string    `json:"alchemy_webhook_id"`
	Address          string    `json:"address"`
	Network          string    `json:"network"`
	IsActive         bool      `json:"is_active"`
	RegisteredAt     time.Time `json:"registered_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
