// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateWallet(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
