// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: token.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (
    code,
    name,
    symbol,
    decimals,
    contract_address,
    network_code,
    token_type,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, code, name, symbol, decimals, contract_address, network_code, token_type, is_active, created_at, updated_at
`

type CreateTokenParams struct {
	Code            string         `json:"code"`
	Name            string         `json:"name"`
	Symbol          string         `json:"symbol"`
	Decimals        int32          `json:"decimals"`
	ContractAddress sql.NullString `json:"contract_address"`
	NetworkCode     string         `json:"network_code"`
	TokenType       string         `json:"token_type"`
	IsActive        bool           `json:"is_active"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.Decimals,
		arg.ContractAddress,
		arg.NetworkCode,
		arg.TokenType,
		arg.IsActive,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ContractAddress,
		&i.NetworkCode,
		&i.TokenType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateToken = `-- name: DeactivateToken :exec
UPDATE tokens
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateToken, id)
	return err
}

const getToken = `-- name: GetToken :one
SELECT id, code, name, symbol, decimals, contract_address, network_code, token_type, is_active, created_at, updated_at FROM tokens
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetToken(ctx context.Context, id uuid.UUID) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ContractAddress,
		&i.NetworkCode,
		&i.TokenType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByCodeAndNetwork = `-- name: GetTokenByCodeAndNetwork :one
SELECT id, code, name, symbol, decimals, contract_address, network_code, token_type, is_active, created_at, updated_at FROM tokens
WHERE code = $1 AND network_code = $2 LIMIT 1
`

type GetTokenByCodeAndNetworkParams struct {
	Code        string `json:"code"`
	NetworkCode string `json:"network_code"`
}

func (q *Queries) GetTokenByCodeAndNetwork(ctx context.Context, arg GetTokenByCodeAndNetworkParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByCodeAndNetwork, arg.Code, arg.NetworkCode)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ContractAddress,
		&i.NetworkCode,
		&i.TokenType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllActiveTokens = `-- name: ListAllActiveTokens :many
SELECT id, code, name, symbol, decimals, contract_address, network_code, token_type, is_active, created_at, updated_at FROM tokens
WHERE is_active = true
ORDER BY network_code ASC, name ASC
`

func (q *Queries) ListAllActiveTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listAllActiveTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.ContractAddress,
			&i.NetworkCode,
			&i.TokenType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTokens = `-- name: ListAllTokens :many
SELECT id, code, name, symbol, decimals, contract_address, network_code, token_type, is_active, created_at, updated_at FROM tokens
ORDER BY network_code ASC, name ASC
`

func (q *Queries) ListAllTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.ContractAddress,
			&i.NetworkCode,
			&i.TokenType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByNetwork = `-- name: ListTokensByNetwork :many
SELECT id, code, name, symbol, decimals, contract_address, network_code, token_type, is_active, created_at, updated_at FROM tokens
WHERE network_code = $1 AND is_active = true
ORDER BY name ASC
`

func (q *Queries) ListTokensByNetwork(ctx context.Context, networkCode string) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listTokensByNetwork, networkCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.ContractAddress,
			&i.NetworkCode,
			&i.TokenType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToken = `-- name: UpdateToken :one
UPDATE tokens
SET name = $2, symbol = $3, decimals = $4, contract_address = $5, token_type = $6, is_active = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, code, name, symbol, decimals, contract_address, network_code, token_type, is_active, created_at, updated_at
`

type UpdateTokenParams struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Symbol          string         `json:"symbol"`
	Decimals        int32          `json:"decimals"`
	ContractAddress sql.NullString `json:"contract_address"`
	TokenType       string         `json:"token_type"`
	IsActive        bool           `json:"is_active"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, updateToken,
		arg.ID,
		arg.Name,
		arg.Symbol,
		arg.Decimals,
		arg.ContractAddress,
		arg.TokenType,
		arg.IsActive,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ContractAddress,
		&i.NetworkCode,
		&i.TokenType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
