// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transaction.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  wallet_id,
  webhook_id,
  event_id,
  network,
  transaction_hash,
  block_number,
  from_address,
  to_address,
  value,
  asset,
  category,
  transaction_type,
  status,
  is_matched,
  gas_fee,
  confirmations,
  contract_address,
  decimals,
  raw_value,
  block_timestamp
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at
`

type CreateTransactionParams struct {
	WalletID        uuid.NullUUID  `json:"wallet_id"`
	WebhookID       string         `json:"webhook_id"`
	EventID         string         `json:"event_id"`
	Network         string         `json:"network"`
	TransactionHash string         `json:"transaction_hash"`
	BlockNumber     string         `json:"block_number"`
	FromAddress     string         `json:"from_address"`
	ToAddress       string         `json:"to_address"`
	Value           string         `json:"value"`
	Asset           string         `json:"asset"`
	Category        string         `json:"category"`
	TransactionType sql.NullString `json:"transaction_type"`
	Status          sql.NullString `json:"status"`
	IsMatched       sql.NullBool   `json:"is_matched"`
	GasFee          sql.NullString `json:"gas_fee"`
	Confirmations   sql.NullInt32  `json:"confirmations"`
	ContractAddress sql.NullString `json:"contract_address"`
	Decimals        sql.NullInt32  `json:"decimals"`
	RawValue        sql.NullString `json:"raw_value"`
	BlockTimestamp  string         `json:"block_timestamp"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.WalletID,
		arg.WebhookID,
		arg.EventID,
		arg.Network,
		arg.TransactionHash,
		arg.BlockNumber,
		arg.FromAddress,
		arg.ToAddress,
		arg.Value,
		arg.Asset,
		arg.Category,
		arg.TransactionType,
		arg.Status,
		arg.IsMatched,
		arg.GasFee,
		arg.Confirmations,
		arg.ContractAddress,
		arg.Decimals,
		arg.RawValue,
		arg.BlockTimestamp,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.WebhookID,
		&i.EventID,
		&i.Network,
		&i.TransactionHash,
		&i.BlockNumber,
		&i.FromAddress,
		&i.ToAddress,
		&i.Value,
		&i.Asset,
		&i.Category,
		&i.TransactionType,
		&i.Status,
		&i.IsMatched,
		&i.GasFee,
		&i.Confirmations,
		&i.ContractAddress,
		&i.Decimals,
		&i.RawValue,
		&i.BlockTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getDepositsByWallet = `-- name: GetDepositsByWallet :many
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE wallet_id = $1 AND transaction_type = 'deposit'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetDepositsByWalletParams struct {
	WalletID uuid.NullUUID `json:"wallet_id"`
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
}

func (q *Queries) GetDepositsByWallet(ctx context.Context, arg GetDepositsByWalletParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getDepositsByWallet, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.WebhookID,
			&i.EventID,
			&i.Network,
			&i.TransactionHash,
			&i.BlockNumber,
			&i.FromAddress,
			&i.ToAddress,
			&i.Value,
			&i.Asset,
			&i.Category,
			&i.TransactionType,
			&i.Status,
			&i.IsMatched,
			&i.GasFee,
			&i.Confirmations,
			&i.ContractAddress,
			&i.Decimals,
			&i.RawValue,
			&i.BlockTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.WebhookID,
		&i.EventID,
		&i.Network,
		&i.TransactionHash,
		&i.BlockNumber,
		&i.FromAddress,
		&i.ToAddress,
		&i.Value,
		&i.Asset,
		&i.Category,
		&i.TransactionType,
		&i.Status,
		&i.IsMatched,
		&i.GasFee,
		&i.Confirmations,
		&i.ContractAddress,
		&i.Decimals,
		&i.RawValue,
		&i.BlockTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByEventId = `-- name: GetTransactionByEventId :one
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE event_id = $1 LIMIT 1
`

func (q *Queries) GetTransactionByEventId(ctx context.Context, eventID string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByEventId, eventID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.WebhookID,
		&i.EventID,
		&i.Network,
		&i.TransactionHash,
		&i.BlockNumber,
		&i.FromAddress,
		&i.ToAddress,
		&i.Value,
		&i.Asset,
		&i.Category,
		&i.TransactionType,
		&i.Status,
		&i.IsMatched,
		&i.GasFee,
		&i.Confirmations,
		&i.ContractAddress,
		&i.Decimals,
		&i.RawValue,
		&i.BlockTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByHash = `-- name: GetTransactionByHash :one
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE transaction_hash = $1 LIMIT 1
`

func (q *Queries) GetTransactionByHash(ctx context.Context, transactionHash string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByHash, transactionHash)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.WebhookID,
		&i.EventID,
		&i.Network,
		&i.TransactionHash,
		&i.BlockNumber,
		&i.FromAddress,
		&i.ToAddress,
		&i.Value,
		&i.Asset,
		&i.Category,
		&i.TransactionType,
		&i.Status,
		&i.IsMatched,
		&i.GasFee,
		&i.Confirmations,
		&i.ContractAddress,
		&i.Decimals,
		&i.RawValue,
		&i.BlockTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalsByWallet = `-- name: GetWithdrawalsByWallet :many
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE wallet_id = $1 AND transaction_type = 'withdrawal'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetWithdrawalsByWalletParams struct {
	WalletID uuid.NullUUID `json:"wallet_id"`
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
}

func (q *Queries) GetWithdrawalsByWallet(ctx context.Context, arg GetWithdrawalsByWalletParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getWithdrawalsByWallet, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.WebhookID,
			&i.EventID,
			&i.Network,
			&i.TransactionHash,
			&i.BlockNumber,
			&i.FromAddress,
			&i.ToAddress,
			&i.Value,
			&i.Asset,
			&i.Category,
			&i.TransactionType,
			&i.Status,
			&i.IsMatched,
			&i.GasFee,
			&i.Confirmations,
			&i.ContractAddress,
			&i.Decimals,
			&i.RawValue,
			&i.BlockTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAddress = `-- name: ListTransactionsByAddress :many
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE to_address = $1 OR from_address = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByAddressParams struct {
	ToAddress string `json:"to_address"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListTransactionsByAddress(ctx context.Context, arg ListTransactionsByAddressParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByAddress, arg.ToAddress, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.WebhookID,
			&i.EventID,
			&i.Network,
			&i.TransactionHash,
			&i.BlockNumber,
			&i.FromAddress,
			&i.ToAddress,
			&i.Value,
			&i.Asset,
			&i.Category,
			&i.TransactionType,
			&i.Status,
			&i.IsMatched,
			&i.GasFee,
			&i.Confirmations,
			&i.ContractAddress,
			&i.Decimals,
			&i.RawValue,
			&i.BlockTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByFromAddress = `-- name: ListTransactionsByFromAddress :many
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE from_address = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByFromAddressParams struct {
	FromAddress string `json:"from_address"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListTransactionsByFromAddress(ctx context.Context, arg ListTransactionsByFromAddressParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByFromAddress, arg.FromAddress, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.WebhookID,
			&i.EventID,
			&i.Network,
			&i.TransactionHash,
			&i.BlockNumber,
			&i.FromAddress,
			&i.ToAddress,
			&i.Value,
			&i.Asset,
			&i.Category,
			&i.TransactionType,
			&i.Status,
			&i.IsMatched,
			&i.GasFee,
			&i.Confirmations,
			&i.ContractAddress,
			&i.Decimals,
			&i.RawValue,
			&i.BlockTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByToAddress = `-- name: ListTransactionsByToAddress :many
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE to_address = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByToAddressParams struct {
	ToAddress string `json:"to_address"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListTransactionsByToAddress(ctx context.Context, arg ListTransactionsByToAddressParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByToAddress, arg.ToAddress, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.WebhookID,
			&i.EventID,
			&i.Network,
			&i.TransactionHash,
			&i.BlockNumber,
			&i.FromAddress,
			&i.ToAddress,
			&i.Value,
			&i.Asset,
			&i.Category,
			&i.TransactionType,
			&i.Status,
			&i.IsMatched,
			&i.GasFee,
			&i.Confirmations,
			&i.ContractAddress,
			&i.Decimals,
			&i.RawValue,
			&i.BlockTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByWallet = `-- name: ListTransactionsByWallet :many
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByWalletParams struct {
	WalletID uuid.NullUUID `json:"wallet_id"`
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
}

func (q *Queries) ListTransactionsByWallet(ctx context.Context, arg ListTransactionsByWalletParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByWallet, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.WebhookID,
			&i.EventID,
			&i.Network,
			&i.TransactionHash,
			&i.BlockNumber,
			&i.FromAddress,
			&i.ToAddress,
			&i.Value,
			&i.Asset,
			&i.Category,
			&i.TransactionType,
			&i.Status,
			&i.IsMatched,
			&i.GasFee,
			&i.Confirmations,
			&i.ContractAddress,
			&i.Decimals,
			&i.RawValue,
			&i.BlockTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedTransactions = `-- name: ListUnmatchedTransactions :many
SELECT id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at FROM transactions
WHERE is_matched = false AND transaction_type = 'deposit'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUnmatchedTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUnmatchedTransactions(ctx context.Context, arg ListUnmatchedTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listUnmatchedTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.WebhookID,
			&i.EventID,
			&i.Network,
			&i.TransactionHash,
			&i.BlockNumber,
			&i.FromAddress,
			&i.ToAddress,
			&i.Value,
			&i.Asset,
			&i.Category,
			&i.TransactionType,
			&i.Status,
			&i.IsMatched,
			&i.GasFee,
			&i.Confirmations,
			&i.ContractAddress,
			&i.Decimals,
			&i.RawValue,
			&i.BlockTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status = $2, confirmations = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, wallet_id, webhook_id, event_id, network, transaction_hash, block_number, from_address, to_address, value, asset, category, transaction_type, status, is_matched, gas_fee, confirmations, contract_address, decimals, raw_value, block_timestamp, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID            uuid.UUID      `json:"id"`
	Status        sql.NullString `json:"status"`
	Confirmations sql.NullInt32  `json:"confirmations"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionStatus, arg.ID, arg.Status, arg.Confirmations)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.WebhookID,
		&i.EventID,
		&i.Network,
		&i.TransactionHash,
		&i.BlockNumber,
		&i.FromAddress,
		&i.ToAddress,
		&i.Value,
		&i.Asset,
		&i.Category,
		&i.TransactionType,
		&i.Status,
		&i.IsMatched,
		&i.GasFee,
		&i.Confirmations,
		&i.ContractAddress,
		&i.Decimals,
		&i.RawValue,
		&i.BlockTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
