// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webhook_registration.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countWebhookRegistrationsByWebhookID = `-- name: CountWebhookRegistrationsByWebhookID :one
SELECT COUNT(*) FROM webhook_registrations
WHERE alchemy_webhook_id = $1 AND is_active = true
`

func (q *Queries) CountWebhookRegistrationsByWebhookID(ctx context.Context, alchemyWebhookID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebhookRegistrationsByWebhookID, alchemyWebhookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookRegistration = `-- name: CreateWebhookRegistration :one
INSERT INTO webhook_registrations (
    wallet_id,
    alchemy_webhook_id,
    address,
    network,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, wallet_id, alchemy_webhook_id, address, network, is_active, registered_at, created_at, updated_at
`

type CreateWebhookRegistrationParams struct {
	WalletID         uuid.UUID `json:"wallet_id"`
	AlchemyWebhookID string    `json:"alchemy_webhook_id"`
	Address          string    `json:"address"`
	Network          string    `json:"network"`
	IsActive         bool      `json:"is_active"`
}

func (q *Queries) CreateWebhookRegistration(ctx context.Context, arg CreateWebhookRegistrationParams) (WebhookRegistration, error) {
	row := q.db.QueryRowContext(ctx, createWebhookRegistration,
		arg.WalletID,
		arg.AlchemyWebhookID,
		arg.Address,
		arg.Network,
		arg.IsActive,
	)
	var i WebhookRegistration
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AlchemyWebhookID,
		&i.Address,
		&i.Network,
		&i.IsActive,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateWebhookRegistration = `-- name: DeactivateWebhookRegistration :exec
UPDATE webhook_registrations
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeactivateWebhookRegistration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateWebhookRegistration, id)
	return err
}

const deactivateWebhookRegistrationByWalletID = `-- name: DeactivateWebhookRegistrationByWalletID :exec
UPDATE webhook_registrations
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE wallet_id = $1
`

func (q *Queries) DeactivateWebhookRegistrationByWalletID(ctx context.Context, walletID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateWebhookRegistrationByWalletID, walletID)
	return err
}

const getAllActiveWebhookRegistrations = `-- name: GetAllActiveWebhookRegistrations :many
SELECT id, wallet_id, alchemy_webhook_id, address, network, is_active, registered_at, created_at, updated_at FROM webhook_registrations
WHERE is_active = true
ORDER BY registered_at DESC
`

func (q *Queries) GetAllActiveWebhookRegistrations(ctx context.Context) ([]WebhookRegistration, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveWebhookRegistrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookRegistration{}
	for rows.Next() {
		var i WebhookRegistration
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AlchemyWebhookID,
			&i.Address,
			&i.Network,
			&i.IsActive,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWalletsWithoutWebhookRegistration = `-- name: GetWalletsWithoutWebhookRegistration :many
SELECT w.id, w.wallet_type, w.blockchain, w.token, w.address, w.public_key, w.private_key, w.balance, w.is_active, w.last_sync_at, w.created_at, w.updated_at FROM wallets w
LEFT JOIN webhook_registrations wr ON w.id = wr.wallet_id AND wr.is_active = true
WHERE wr.id IS NULL AND w.wallet_type = $1 AND w.is_active = true
ORDER BY w.created_at DESC
`

func (q *Queries) GetWalletsWithoutWebhookRegistration(ctx context.Context, walletType string) ([]Wallet, error) {
	rows, err := q.db.QueryContext(ctx, getWalletsWithoutWebhookRegistration, walletType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.WalletType,
			&i.Blockchain,
			&i.Token,
			&i.Address,
			&i.PublicKey,
			&i.PrivateKey,
			&i.Balance,
			&i.IsActive,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookRegistrationByAddress = `-- name: GetWebhookRegistrationByAddress :one
SELECT id, wallet_id, alchemy_webhook_id, address, network, is_active, registered_at, created_at, updated_at FROM webhook_registrations
WHERE address = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetWebhookRegistrationByAddress(ctx context.Context, address string) (WebhookRegistration, error) {
	row := q.db.QueryRowContext(ctx, getWebhookRegistrationByAddress, address)
	var i WebhookRegistration
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AlchemyWebhookID,
		&i.Address,
		&i.Network,
		&i.IsActive,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookRegistrationByWalletID = `-- name: GetWebhookRegistrationByWalletID :one
SELECT id, wallet_id, alchemy_webhook_id, address, network, is_active, registered_at, created_at, updated_at FROM webhook_registrations
WHERE wallet_id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetWebhookRegistrationByWalletID(ctx context.Context, walletID uuid.UUID) (WebhookRegistration, error) {
	row := q.db.QueryRowContext(ctx, getWebhookRegistrationByWalletID, walletID)
	var i WebhookRegistration
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AlchemyWebhookID,
		&i.Address,
		&i.Network,
		&i.IsActive,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookRegistrationsByWebhookID = `-- name: GetWebhookRegistrationsByWebhookID :many
SELECT id, wallet_id, alchemy_webhook_id, address, network, is_active, registered_at, created_at, updated_at FROM webhook_registrations
WHERE alchemy_webhook_id = $1 AND is_active = true
ORDER BY registered_at DESC
`

func (q *Queries) GetWebhookRegistrationsByWebhookID(ctx context.Context, alchemyWebhookID string) ([]WebhookRegistration, error) {
	rows, err := q.db.QueryContext(ctx, getWebhookRegistrationsByWebhookID, alchemyWebhookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookRegistration{}
	for rows.Next() {
		var i WebhookRegistration
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AlchemyWebhookID,
			&i.Address,
			&i.Network,
			&i.IsActive,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
