// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: withdrawal_request.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createWithdrawalRequest = `-- name: CreateWithdrawalRequest :one
INSERT INTO withdrawal_requests (
    customer_id,
    from_wallet_id,
    to_address,
    network,
    token,
    requested_amount,
    fee_amount,
    actual_amount,
    status,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at
`

type CreateWithdrawalRequestParams struct {
	CustomerID      string         `json:"customer_id"`
	FromWalletID    uuid.UUID      `json:"from_wallet_id"`
	ToAddress       string         `json:"to_address"`
	Network         string         `json:"network"`
	Token           string         `json:"token"`
	RequestedAmount string         `json:"requested_amount"`
	FeeAmount       sql.NullString `json:"fee_amount"`
	ActualAmount    sql.NullString `json:"actual_amount"`
	Status          string         `json:"status"`
	Notes           sql.NullString `json:"notes"`
}

func (q *Queries) CreateWithdrawalRequest(ctx context.Context, arg CreateWithdrawalRequestParams) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, createWithdrawalRequest,
		arg.CustomerID,
		arg.FromWalletID,
		arg.ToAddress,
		arg.Network,
		arg.Token,
		arg.RequestedAmount,
		arg.FeeAmount,
		arg.ActualAmount,
		arg.Status,
		arg.Notes,
	)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromWalletID,
		&i.ToAddress,
		&i.Network,
		&i.Token,
		&i.RequestedAmount,
		&i.FeeAmount,
		&i.ActualAmount,
		&i.Status,
		&i.TransactionID,
		&i.Notes,
		&i.ErrorMessage,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveWithdrawalByCustomer = `-- name: GetActiveWithdrawalByCustomer :one
SELECT id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at FROM withdrawal_requests
WHERE customer_id = $1 AND status IN ('pending', 'processing')
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveWithdrawalByCustomer(ctx context.Context, customerID string) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, getActiveWithdrawalByCustomer, customerID)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromWalletID,
		&i.ToAddress,
		&i.Network,
		&i.Token,
		&i.RequestedAmount,
		&i.FeeAmount,
		&i.ActualAmount,
		&i.Status,
		&i.TransactionID,
		&i.Notes,
		&i.ErrorMessage,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveWithdrawalByToAddress = `-- name: GetActiveWithdrawalByToAddress :one
SELECT id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at FROM withdrawal_requests
WHERE LOWER(to_address) = LOWER($1) AND status IN ('pending', 'processing')
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveWithdrawalByToAddress(ctx context.Context, lower string) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, getActiveWithdrawalByToAddress, lower)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromWalletID,
		&i.ToAddress,
		&i.Network,
		&i.Token,
		&i.RequestedAmount,
		&i.FeeAmount,
		&i.ActualAmount,
		&i.Status,
		&i.TransactionID,
		&i.Notes,
		&i.ErrorMessage,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProcessingWithdrawalByToAddress = `-- name: GetProcessingWithdrawalByToAddress :one
SELECT id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at FROM withdrawal_requests
WHERE LOWER(to_address) = LOWER($1) AND status = 'processing'
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetProcessingWithdrawalByToAddress(ctx context.Context, lower string) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, getProcessingWithdrawalByToAddress, lower)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromWalletID,
		&i.ToAddress,
		&i.Network,
		&i.Token,
		&i.RequestedAmount,
		&i.FeeAmount,
		&i.ActualAmount,
		&i.Status,
		&i.TransactionID,
		&i.Notes,
		&i.ErrorMessage,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalRequest = `-- name: GetWithdrawalRequest :one
SELECT id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at FROM withdrawal_requests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWithdrawalRequest(ctx context.Context, id uuid.UUID) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, getWithdrawalRequest, id)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromWalletID,
		&i.ToAddress,
		&i.Network,
		&i.Token,
		&i.RequestedAmount,
		&i.FeeAmount,
		&i.ActualAmount,
		&i.Status,
		&i.TransactionID,
		&i.Notes,
		&i.ErrorMessage,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalRequestByTxHash = `-- name: GetWithdrawalRequestByTxHash :one
SELECT id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at FROM withdrawal_requests
WHERE LOWER(tx_hash) = LOWER($1) LIMIT 1
`

func (q *Queries) GetWithdrawalRequestByTxHash(ctx context.Context, lower string) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, getWithdrawalRequestByTxHash, lower)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromWalletID,
		&i.ToAddress,
		&i.Network,
		&i.Token,
		&i.RequestedAmount,
		&i.FeeAmount,
		&i.ActualAmount,
		&i.Status,
		&i.TransactionID,
		&i.Notes,
		&i.ErrorMessage,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalRequestsByWallet = `-- name: GetWithdrawalRequestsByWallet :many
SELECT id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at FROM withdrawal_requests
WHERE from_wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetWithdrawalRequestsByWalletParams struct {
	FromWalletID uuid.UUID `json:"from_wallet_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) GetWithdrawalRequestsByWallet(ctx context.Context, arg GetWithdrawalRequestsByWalletParams) ([]WithdrawalRequest, error) {
	rows, err := q.db.QueryContext(ctx, getWithdrawalRequestsByWallet, arg.FromWalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WithdrawalRequest{}
	for rows.Next() {
		var i WithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.FromWalletID,
			&i.ToAddress,
			&i.Network,
			&i.Token,
			&i.RequestedAmount,
			&i.FeeAmount,
			&i.ActualAmount,
			&i.Status,
			&i.TransactionID,
			&i.Notes,
			&i.ErrorMessage,
			&i.TxHash,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWithdrawals = `-- name: ListPendingWithdrawals :many
SELECT id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at FROM withdrawal_requests
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingWithdrawals(ctx context.Context) ([]WithdrawalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWithdrawals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WithdrawalRequest{}
	for rows.Next() {
		var i WithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.FromWalletID,
			&i.ToAddress,
			&i.Network,
			&i.Token,
			&i.RequestedAmount,
			&i.FeeAmount,
			&i.ActualAmount,
			&i.Status,
			&i.TransactionID,
			&i.Notes,
			&i.ErrorMessage,
			&i.TxHash,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalRequestsByCustomer = `-- name: ListWithdrawalRequestsByCustomer :many
SELECT id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at FROM withdrawal_requests
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWithdrawalRequestsByCustomerParams struct {
	CustomerID string `json:"customer_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListWithdrawalRequestsByCustomer(ctx context.Context, arg ListWithdrawalRequestsByCustomerParams) ([]WithdrawalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listWithdrawalRequestsByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WithdrawalRequest{}
	for rows.Next() {
		var i WithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.FromWalletID,
			&i.ToAddress,
			&i.Network,
			&i.Token,
			&i.RequestedAmount,
			&i.FeeAmount,
			&i.ActualAmount,
			&i.Status,
			&i.TransactionID,
			&i.Notes,
			&i.ErrorMessage,
			&i.TxHash,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWithdrawalRequestFees = `-- name: UpdateWithdrawalRequestFees :one
UPDATE withdrawal_requests
SET 
    fee_amount = $2,
    actual_amount = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at
`

type UpdateWithdrawalRequestFeesParams struct {
	ID           uuid.UUID      `json:"id"`
	FeeAmount    sql.NullString `json:"fee_amount"`
	ActualAmount sql.NullString `json:"actual_amount"`
}

func (q *Queries) UpdateWithdrawalRequestFees(ctx context.Context, arg UpdateWithdrawalRequestFeesParams) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, updateWithdrawalRequestFees, arg.ID, arg.FeeAmount, arg.ActualAmount)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromWalletID,
		&i.ToAddress,
		&i.Network,
		&i.Token,
		&i.RequestedAmount,
		&i.FeeAmount,
		&i.ActualAmount,
		&i.Status,
		&i.TransactionID,
		&i.Notes,
		&i.ErrorMessage,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWithdrawalRequestStatus = `-- name: UpdateWithdrawalRequestStatus :one
UPDATE withdrawal_requests
SET 
    status = $2,
    transaction_id = COALESCE($3, transaction_id),
    error_message = COALESCE($4, error_message),
    tx_hash = COALESCE($5, tx_hash),
    completed_at = CASE 
        WHEN $2 IN ('completed', 'failed', 'cancelled') THEN CURRENT_TIMESTAMP 
        ELSE completed_at 
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, customer_id, from_wallet_id, to_address, network, token, requested_amount, fee_amount, actual_amount, status, transaction_id, notes, error_message, tx_hash, created_at, completed_at, updated_at
`

type UpdateWithdrawalRequestStatusParams struct {
	ID            uuid.UUID      `json:"id"`
	Status        string         `json:"status"`
	TransactionID uuid.NullUUID  `json:"transaction_id"`
	ErrorMessage  sql.NullString `json:"error_message"`
	TxHash        sql.NullString `json:"tx_hash"`
}

func (q *Queries) UpdateWithdrawalRequestStatus(ctx context.Context, arg UpdateWithdrawalRequestStatusParams) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, updateWithdrawalRequestStatus,
		arg.ID,
		arg.Status,
		arg.TransactionID,
		arg.ErrorMessage,
		arg.TxHash,
	)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromWalletID,
		&i.ToAddress,
		&i.Network,
		&i.Token,
		&i.RequestedAmount,
		&i.FeeAmount,
		&i.ActualAmount,
		&i.Status,
		&i.TransactionID,
		&i.Notes,
		&i.ErrorMessage,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
